blog/blog/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [

    url(r'^$', views.index, name='index'),
    url(r'^nosotros/$', views.us, name='us'),
    url(r'^servicios/$', views.services, name='services'),
    url(r'^portafolio/$', views.PortfolioView.as_view(), name='portfolio'),
    url(r'^portafolio/(?P<slug>[-\w]+)/$', views.PortfolioDetailView.as_view(), name='portfolio-detail'),
    url(r'^contacto/$', views.contact, name='contact'),
    url(r'^blog$', views.Blog.as_view(), name='blog'),
    url(r'^posts/(?P<slug>[-\w]+)/$', views.BlogDetailView.as_view(), name='post'),

]

blog/config/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static

admin.autodiscover()

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('blog.urls')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/blog/models.py
from ckeditor_uploader.fields import RichTextUploadingField
from django.contrib.auth import get_user_model
from django.db import models
from django.template.defaultfilters import slugify


class BaseModel(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


def upload_fotos(instance, filename):
    return "{0}/{1}".format(type(instance).__name__.lower(), filename)


class Post(BaseModel):
    title = models.CharField(max_length=200)
    description = models.TextField()
    content = RichTextUploadingField()
    image = models.ImageField(upload_to=upload_fotos, blank=True)
    video = models.CharField(max_length=200, blank=True)
    slug = models.SlugField(unique=True, editable=False)
    author = models.ForeignKey(get_user_model())
    published = models.DateField()

    class Meta:
        ordering = ["-published"]

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.pk:
            self.slug = slugify(self.title)[:50]
        super(Post, self).save(*args, **kwargs)


class PostPhoto(BaseModel):
    post = models.ForeignKey(Post)
    title = models.CharField(max_length=100)
    photo = models.ImageField(upload_to=upload_fotos, blank=True)

    def __str__(self):
        return self.title


class Portfolio(BaseModel):
    title = models.CharField(max_length=200)
    content = RichTextUploadingField()
    image = models.ImageField(upload_to=upload_fotos)
    video = models.CharField(max_length=200, blank=True, null=True)
    slug = models.SlugField(editable=False)
    author = models.ForeignKey(get_user_model(), blank=True, null=True)
    created_by = models.CharField(max_length=200, default="Arquetitek")
    completed = models.DateField()
    services = models.CharField(max_length=200)
    client = models.CharField(max_length=200)
    client_url = models.URLField(blank=True, null=True)
    photos_col_size = models.IntegerField(default=3)

    class Meta:
        ordering = ["-completed"]

    def __str__(self):
        return self.title

    def get_services(self):
        return self.services.split(",")

    def save(self, *args, **kwargs):
        if not self.pk:
            self.slug = slugify(self.title)[:50]
        super(Portfolio, self).save(*args, **kwargs)


class PhotoPortfolio(BaseModel):
    portfolio = models.ForeignKey(Portfolio)
    title = models.CharField(max_length=100)
    photo = models.ImageField(upload_to=upload_fotos, blank=True)
    order = models.IntegerField(default=0)

    class Meta:
        ordering = ["order"]

    def __str__(self):
        return self.title

blog/blog/forms.py
from django import forms


class Form(forms.Form):
    name = forms.CharField(max_length=100)
    email = forms.EmailField()
    phone = forms.CharField()
    message = forms.CharField(widget=forms.Textarea)

    def __init__(self, *args, **kwargs):
        super(Form, self).__init__(*args, **kwargs)
        self.fields['name'].widget.attrs['class'] = 'sm-form-control required'
        self.fields['email'].widget.attrs['class'] = 'required email sm-form-control'
        self.fields['phone'].widget.attrs['class'] = 'sm-form-control'
        self.fields['message'].widget.attrs['class'] = 'required sm-form-control'

blog/blog/views.py
from django.contrib import messages
from django.core.mail import EmailMultiAlternatives
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.template.loader import render_to_string
from django.views.generic import DetailView
from django.views.generic.list import ListView

from .forms import Form
from .models import Post, PostPhoto, Portfolio, PhotoPortfolio


# Create your views here.
class Blog(ListView):
    model = Post
    template_name = 'blog.html'
    paginate_by = 6
    context_object_name = "post_list"


def get_queryset(self, **kwargs):
    return Post.objects.filter(presentar=True).order_by("-published")


class BlogDetailView(DetailView):
    model = Post
    template_name = 'blog-detalle.html'
    context_object_name = 'post'

    def get_context_data(self, **kwargs):
        context = super(BlogDetailView, self).get_context_data(**kwargs)
        context["gallery"] = PostPhoto.objects.filter(post=self.object)
        return context


class PortfolioView(ListView):
    model = Portfolio
    template_name = 'portfolio.html'
    paginate_by = 6


class PortfolioDetailView(DetailView):
    model = Portfolio
    template_name = 'portfolio-detail.html'

    def get_context_data(self, **kwargs):
        context = super(PortfolioDetailView, self).get_context_data(**kwargs)
        context["gallery"] = PhotoPortfolio.objects.filter(portfolio=self.object)
        context["portafolio_related"] = Portfolio.objects.exclude(pk=self.object.pk)
        return context


def index(request):
    return render(request, 'index.html')


def us(request):
    return render(request, 'nosotros.html', )


def services(request):
    return render(request, 'servicios.html', )


def contact(request):
    if request.method == 'POST':
        form = Form(request.POST)
        if form.is_valid():
            affair = 'Mensaje de Arquetitek'
            name = form.cleaned_data["name"]
            email = form.cleaned_data['email']
            phone = form.cleaned_data["phone"]
            message = form.cleaned_data["message"]
            ctx = {'name': name, 'email': email, 'phone': phone, 'message': message}
            message_html = render_to_string('datos_mail_admin.html', ctx)
            mail = EmailMultiAlternatives(affair, message_html, cc=(email,), to=['juniorrivasmendoza@gmail.com'])
            mail.attach_alternative(message_html, 'text/html')
            mail.send()
            messages.success(request, 'Su message fue enviado con Exito', extra_tags='alert')
            return HttpResponseRedirect('index.html')
        else:
            messages.warning(request, 'Please correct the error below.')
    else:
        form = Form()
    return render(request, 'contacto.html', {'form': form}, )

blog/blog/templates/blog-detalle.html
{% extends "base.html" %}
{% load static %}


{% block page_title %}{{ post.title }} | Blog |{% endblock %}
{% block meta_tags %}
    <meta name="description" content="{{ post.description }}"/>
{% endblock %}
{% block main %}
    <section id="content">
        {% if post.image %}
            <div class="entry-image">
                <a href="#"><img src="{{ post.image.url }}" alt="{{ post.title }}"></a>
            </div><!-- .entry-image end -->
        {% endif %}
        <div class="content-wrap">
            <div class="container clearfix">
                <div class="single-post nobottommargin">
                    {% if post.postphoto_set.count %}
                        <div class=" col_full portfolio-single-image">
                            <div class="fslider" data-arrows="true" data-animation="slide">
                                <div class="flexslider">
                                    <div class="slider-wrap">
                                        {% for postphoto in post.postphoto_set.all %}
                                            {{ postphoto }}
                                            {% if postphoto.photo %}
                                            <div class="slide"><a><img
                                                    src="{{ postphoto.photo.url }}" alt="{{ postphoto.photo.title }}"></a>
                                            </div>
                                            {% endif %}
                                        {% endfor %}
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% elif post.video %}
                        <iframe width="560" height="315" src="https://www.youtube.com/embed/{{ post.video }}"
                                frameborder="0"
                                allowfullscreen></iframe>

                    {% endif %}
                    <div class="postcontent nobottommargin clearfix">

                    <div class="entry clearfix">

                        <!-- Entry Title
                        ============================================= -->
                        <div class="entry-title">
                            <h2>{{ post.title }}</h2><br>
                        </div><!-- .entry-title end -->

                        <!-- Entry Meta
                        ============================================= -->
                        <ul class="entry-meta clearfix">
                            <li> {{ post.published }}</li>
                            <li> {{ post.author.get_full_name }}</li>
                            <li> {{ post.description }}</li>
                        </ul><!-- .entry-meta end -->

                        <!-- Entry Content
                        ============================================= -->
                        <div class="entry-content notopmargin">
                            {{ post.content|safe }}
                        </div>
                    </div><!-- .entry end -->


                </div>

                <!-- Sidebar
                ============================================= -->
                <div class="sidebar nobottommargin col_last clearfix">
                    <div class="sidebar-widgets-wrap">

                        <!--

                            <h4>Twitter Feed</h4>
                            <ul class="iconlist twitter-feed" data-username="envato" data-count="2">
                                <li></li>
                            </ul>

                                <a class="twitter-timeline" href="https://twitter.com/arquetitek"><h4>Tweets by Arquetitek</h4></a>
                                    <script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>



                            <a href="#" class="btn btn-default btn-sm fright">Follow Us on Twitter</a>

                        </div>-->
                        <div class="widget widget-twitter-feed clearfix">
                            <div style="height:500px; overflow:scroll;">
                                <a class="twitter-timeline" href="https://twitter.com/arquetitek"><h4>Tweets by
                                    Arquetitek</h4></a>
                                <script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
                            </div>
                        </div>

                        <div class="widget clearfix">

                            <h4>Instagram Arquetitek</h4>
                            <script src="https://snapwidget.com/js/snapwidget.js"></script>
                            <iframe src="https://snapwidget.com/embed/430556" class="snapwidget-widget"
                                    allowTransparency="false" frameborder="0" scrolling="no"
                                    style="border:none; overflow:hidden; width:100%;"></iframe>


                        </div>

                    </div>

                    <div class="widget clearfix">
                        {% for post in content_portfolio %}
                            <div class="tabs nobottommargin clearfix" id="sidebar-tabs">
                                <div class="tab-container">

                                    <div class="tab-content clearfix" id="tabs-1">
                                        <div id="popular-post-list-sidebar">
                                            <div class="spost clearfix">
                                                <div class="entry-image">
                                                    <a href="#" class="nobg"><img class="img-circle"
                                                                                  src="{{ post.image.url }}"
                                                                                  alt=""></a>
                                                </div>
                                                <div class="entry-c">
                                                    <div class="entry-title">
                                                        <h4><a href="{% url 'post' post.slug %}">{{ post.title }}</a>
                                                        </h4>
                                                    </div>
                                                    <ul class="entry-meta">
                                                        <li><i class="icon-comments-alt"></i>35 coments</li>
                                                    </ul>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    </div>

                </div>
            </div><!-- .sidebar end -->
        </div>
        </div>

    </section><!-- #content end -->

{% endblock %}

blog/blog/templates/contacto.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Contacto |{% endblock %}
{% block main %}

<!-- Page Title
============================================= -->
<section id="page-title" class="page-title-parallax page-title-dark"
         style="padding: 150px 0 150px 0; background-image: url('{% static 'images/about/contacto.jpg' %}'); background-size: cover; background-position: center center;"
         data-stellar-background-ratio="0.4">


    <div class="container clearfix">
        <h1 style="float:right;">Contáctenos</h1>
        <div class="clear"></div>
        <span style="float:right;">Nuestro equipo te ofrecerá las mejores soluciones</span>
    </div>

</section><!-- #page-title end -->

<!-- Content
============================================= -->
<section id="content">

    <div class="content-wrap">

        <div class="container clearfix">

            <!-- Postcontent
            ============================================= -->
            <div class="postcontent nobottommargin">

                {% if messages %}
                <ul class="messages">
                    {% for message in messages %}
                    <li
                            {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}
                    </li>
                    {% endfor %}
                </ul>
                {% endif %}

                <h3>Envíenos un mensaje</h3>

                <div class="contact-widget">


                    <form class="nobottommargin" method="post"> {% csrf_token %}

                        <div class="form-process"></div>

                        <div class="col_one_third">

                            <label for="id_nombre">Nombre
                                <small>*</small>
                            </label>

                            {{ form.name }}

                        </div>

                        <div class="col_one_third">
                            <label for="id_email">Email
                                <small>*</small>
                            </label>
                            {{ form.email}}
                        </div>

                        <div class="col_one_third col_last">
                            <label for="id_telefono">Teléfono</label>
                            {{ form.phone }}
                        </div>

                        <div class="col_full">
                            <label for="id_mensaje">Mensaje
                                <small>*</small>
                            </label>
                            {{ form.message }}
                        </div>


                        <input class="button button-3d nomargin" type="submit" value="Enviar Mensaje"/>

                    </form>

                </div>

            </div><!-- .postcontent end -->

            <!-- Sidebar
            ============================================= -->
            <div class="sidebar col_last nobottommargin">

                <abbr title="Phone Number"><strong>Contacto Venezuela</strong><br>
                    <strong>Telefono:</strong></abbr> 0424-210.9499<br>
                <abbr title="Email Address"><strong>Email:</strong></abbr> info.ve@arquetitek.com<br>
                <abbr title="Email Address"><strong>Email:</strong></abbr> contacto@arquetitek.com<br><br>

                <abbr title="Phone Number"><strong>Contacto Ecuador</strong><br>
                    <strong>Telefono:</strong></abbr> +593 98788 0066<br>
                <abbr title="Email Address"><strong>Email:</strong></abbr> info.ec@arquetitek.com<br><br>

                <abbr title="Phone Number"><strong>Contacto Panamá</strong><br>
                    <strong>Telefono:</strong></abbr> 0424-210.9499<br>
                <abbr title="Email Address"><strong>Email:</strong></abbr> info.pa@arquetitek.com<br>

                <div class="widget noborder notoppadding">

                    <a href="https://www.facebook.com/Arquetitek/" class="social-icon si-small si-dark si-facebook">
                        <i class="icon-facebook"></i>
                        <i class="icon-facebook"></i>
                    </a>

                    <a href="https://twitter.com/arquetitek" class="social-icon si-small si-dark si-twitter">
                        <i class="icon-twitter"></i>
                        <i class="icon-twitter"></i>
                    </a>

                    <a href="https://www.instagram.com/arquetitek/" class="social-icon si-small si-dark si-forrst">
                        <i class="icon-instagram"></i>
                        <i class="icon-instagram"></i>
                    </a>

                    <!--<a href="#" class="social-icon si-small si-dark si-pinterest">
                        <i class="icon-pinterest"></i>
                        <i class="icon-pinterest"></i>
                    </a>

                    <a href="#" class="social-icon si-small si-dark si-gplus">
                        <i class="icon-gplus"></i>
                        <i class="icon-gplus"></i>
                    </a>-->

                </div>

            </div><!-- .sidebar end -->

        </div>

    </div>

</section><!-- #content end -->

{% endblock %}

blog/blog/templates/datos_mail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title> </title></head>
<body>
    Gracias por sus comentarios.
    <br>
    informacion recibida:
    <p>Nombre: {{form.name}}</p>
    <p>Email: {{form.email}}</p>
    <p>telefono: {{form.phone}}</p>
    <p>Mensaje: {{form.message}}</p>

    estaremos en contacto con usted..

</body>
</html>

blog/blog/templates/datos_mail_admin.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
    informacion recibida:
    <p>Nombre: {{name}}</p>
    <p>Email: {{email}}</p>
    <p>telefono: {{phone}}</p>
    <p>Mensaje: {{message}}</p>

</body>
</html>

blog/blog/templates/portafolio.html
{% extends 'base.html' %}
{% load static %}

<title>{% block title %}Portfolio - Mixed Masonry | Canvas{% endblock title %}</title>

{% block main %}


<div class="clear"></div>

<section id="content">

    <div class="content-wrap">

        <!-- portafolios
         ============================================= -->

        <div id="posts" class="post-grid grid-container post-masonry post-masonry-full clearfix">
            {% for portafolio in object_list %}
            <div class="entry clearfix">
                {% if portafolio.imagen %}
                <div class="entry-image">
                    <div class="entry-image">
                    </div>

                    <a href="{{ portafolio.imagen.url }}" data-lightbox="image"><img class="image_fade"
                                                                                     src="{{ portafolio.imagen.url }}"
                                                                                     alt="Standard portafolio with Image"></a>
                </div>
                {% elif portafolio.video %}

                <div class="entry-image">
                    <iframe width="560" height="315"
                            src="https://www.youtube.com/embed/{{ portafolio.video }}"
                            frameborder="0"
                            allowfullscreen></iframe>
                </div>
                {% endif %}

                <div class="entry-title">
                    <h2><a><a href="{% url 'portafolio-detalle' portafolio.slug %}">{{ portafolio.titulo }}</a></a></h2>
                </div>
                <ul class="entry-meta clearfix">
                    <li>{{ portafolio.publicado }}</li>
                    <li>{{ portafolio.autor }}</li>
                    <li><a href="#"><i class="icon-camera-retro"></i></a></li>
                </ul>
                <div class="entry-content">
                    <p>{{ portafolio.descripcion }}</p>
                    <a href="{% url 'portafolio-detalle' portafolio.slug %}" class="more-link">Read More</a>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>

</section>

{% endblock %}|

blog/blog/templates/portfolio-detail.html
{% extends "base.html" %}
{% load static %}

{% block page_title %}Portafolio |{% endblock %}

{% block main %}

<!-- Content
============================================= -->
<section id="content">

    <!-- Portfolio Single Gallery Thumbs
    ============================================= -->
    <div class="col_full portfolio-single-image masonry-thumbs col-{{ portfolio.photos_col_size }}" data-big="2" data-lightbox="gallery">
        {% if portfolio.photoportfolio_set.all %}
            {% for photoportfolio in portfolio.photoportfolio_set.all %}
            <a href="{{ photoportfolio.photo.url }}" data-lightbox="gallery-item"><img class="image_fade" src="{{ photoportfolio.photo.url }}" alt="{{ photoportfolio.title }}"></a>
            {% endfor %}
        {% else %}
            <a href="{{ portfolio.image.url }}" data-lightbox="gallery-item"><img class="image_fade" src="{{ portfolio.image.url }}" alt="{{ portfolio.title }}"></a>
        {% endif %}

    </div><!-- .portfolio-single-image end -->

    <div class="content-wrap">

        <div class="container clearfix">


            <div class="single-post nobottommargin">

                <div class="col_one_third nobottommargin">

                    <!-- Portfolio Single - Meta
                    ============================================= -->
                    <div class="panel panel-default events-meta">
                        <div class="panel-body">
                            <ul class="portfolio-meta nobottommargin">
                                <li><span><i class="icon-user"></i>Creado por:</span> {{ portfolio.created_by }}</li>
                                <li><span><i
                                        class="icon-calendar3"></i>Fecha:</span> {{ portfolio.completed|date:"N Y" }}
                                </li>
                                {% for service in portfolio.get_services %}
                                <li>
                                    <span>{% if forloop.first %}
                                        <i class="icon-lightbulb"></i>Servicios:{% endif %}</span>
                                    {{ service }}</li>
                                {% endfor %}
                                <li><span><i class="icon-link"></i>Cliente:</span> <a
                                        href="{{ portfolio.client_url }}">{{ portfolio.client }}</a></li>
                            </ul>
                        </div>
                    </div>
                    <!-- Portfolio Single - Meta End -->

                    <!-- Portfolio Single - Share
                    ============================================= -->
                    <div class="si-share noborder clearfix">
                        <span>Share: </span>
                        <div>
                            <a href="https://www.facebook.com/Arquetitek/"
                               class="social-icon si-borderless si-facebook">
                                <i class="icon-facebook"></i>
                                <i class="icon-facebook"></i>
                            </a>
                            <a href="https://twitter.com/arquetitek" class="social-icon si-borderless si-twitter">
                                <i class="icon-twitter"></i>
                                <i class="icon-twitter"></i>
                            </a>

                             <a href="https://www.instagram.com/arquetitek/"
                               class="social-icon si-borderless si-forrst">
                                <i class="icon-instagram"></i>
                                <i class="icon-instagram"></i>
                            </a>


                           <!-- <a href="#" class="social-icon si-borderless si-pinterest">
                                <i class="icon-pinterest"></i>
                                <i class="icon-pinterest"></i>
                            </a>

                            <a href="#" class="social-icon si-borderless si-gplus">
                                <i class="icon-gplus"></i>
                                <i class="icon-gplus"></i>
                            </a>

                            <a href="#" class="social-icon si-borderless si-rss">
                                <i class="icon-rss"></i>
                                <i class="icon-rss"></i>
                            </a>
                            <a href="#" class="social-icon si-borderless si-email3">
                                <i class="icon-email3"></i>
                                <i class="icon-email3"></i>
                            </a>-->

                        </div>
                    </div>
                    <!-- Portfolio Single - Share End -->

                </div>

                <!-- Portfolio Single Content
                ============================================= -->
                <div class="col_two_third portfolio-single-content col_last nobottommargin">

                    <!-- Portfolio Single - Description
                    ============================================= -->
                    <div class="fancy-title title-dotted-border">
                        <h2>Project {{ portfolio.title }} Info:</h2>
                    </div>
                    {{ portfolio.content|safe }}
                </div>
                <!-- Portfolio Single - Description End -->

            </div><!-- .portfolio-single-content end -->

            <div class="clear"></div>

            <div class="divider divider-center"><i class="icon-circle"></i></div>

            <!-- Related Portfolio Items
            ============================================= -->

            <h4>Related Projects:</h4>

            <div id="related-portfolio" class="owl-carousel portfolio-carousel carousel-widget" data-margin="30"
                 data-nav="false" data-autoplay="5000" data-items-xxs="1" data-items-xs="2" data-items-sm="3"
                 data-items-lg="4">
                {% for portfolio in portafolio_related %}
                <div class="oc-item">
                    <div class="iportfolio">

                        <div class="portfolio-image">

                            <a href="{% url 'portfolio' %}">
                                <img src="{{ portfolio.image.url }}" alt="Open Imagination">
                            </a>

                            <div class="portfolio-overlay">
                                <a href="{{ portfolio.image.url }}" class="left-icon"
                                   data-lightbox="image"><i
                                        class="icon-line-plus"></i></a>
                                <a href="{% url 'portfolio-detail' portfolio.slug %}" class="right-icon"><i
                                        class="icon-line-ellipsis"></i></a>
                            </div>

                        </div><!-- .portfolio-carousel end -->
                        <div class="portfolio-desc">
                                <h3><a href="{% url 'portfolio-detail' portfolio.slug %}">{{ portfolio.title }}</a></h3>
{#                                <span><a href="#">UI Elements</a>, <a href="#">Icons</a></span>#}
                            </div>

                    </div>

                </div>
                {% endfor %}
            </div>
        </div>
    </div>

</section><!-- #content end -->


{% endblock %}